# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-SubjectMap
version:      0.6
version_from: lib/MARC/SubjectMap.pm
installdirs:  site
requires:
    BerkeleyDB:                    0
    Class::Accessor:               0
    MARC::Record:                  0
    Storable:                      0
    Test::Exception:               0
    Test::More:                    0
    XML::SAX:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
