--- #YAML:1.0
name:                MARC-SubjectMap
version:             0.92
abstract:            framework for translating subject headings
license:             ~
author:              
    - Ed Summers <ehs@pobox.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    BerkeleyDB:                    0
    Class::Accessor:               0
    MARC::Record:                  0
    Storable:                      0
    Test::Exception:               0
    Test::More:                    0
    XML::SAX:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
